/* ============================================================================
 * ⚠️  MOCK DATA — TEMPORARY
 * ----------------------------------------------------------------------------
 * كل البيانات في هذا الملف وهمية لغرض العرض فقط (Supervisor / HR / Courier).
 * عند ربط الباك إند: احذف هذا الملف بالكامل، واجلب البيانات من الـ API.
 *
 * الملفات الأخرى التي تحتوي بيانات وهمية مؤقتة:
 *   - src/context/AuthContext.jsx            (DEMO_USERS)
 *   - src/constants/mockAttendance.js        (حضور المناديب)
 *   - src/constants/mockDashboard.js         (بيانات داشبورد المندوب)
 *   - src/constants/supervisors.js           (قائمة المشرفين)
 *   - src/constants/companies.js             (الشركات والمخازن)
 * ========================================================================== */

import { REQUEST_STATUS, CANCEL_REASON, OPERATION_STATUS } from '@/constants/requestStatus';

/* ----------------------------------------------------------------------------
 * طلبات التسجيل (Hiring applications)
 * -------------------------------------------------------------------------- */
export const MOCK_HIRING_REQUESTS = [
  {
    id: 'APP-2026-1043',
    fullName: 'عبدالله محمد الغامدي',
    nationalId: '1098765432',
    nationality: 'سعودي',
    dateOfBirth: '1994-08-16',
    phone: '501234567',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'أ ب ج ١٢٣٤',
    vehicleType: 'Sedan',
    bankName: 'Al Rajhi Bank',
    iban: 'SA0000000000000000000000',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_SUPERVISOR,
    companyId: null,
    warehouseId: null,
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: null,
    supervisorRejectReason: '',
    createdAt: '2026-09-06',
  },
  {
    id: 'APP-2026-1044',
    fullName: 'سعيد فهد القحطاني',
    nationalId: '1087654321',
    nationality: 'مصري',
    passportNumber: 'A12345678',
    dateOfBirth: '1991-02-11',
    phone: '559876543',
    city: 'Jeddah',
    supervisorId: 'sup-fahad',
    supervisorName: 'فهد العتيبي',
    supervisorPhone: '+966501234567',
    hasVehicle: false,
    vehiclePlate: '',
    vehicleType: '',
    bankName: 'Riyad Bank',
    iban: 'SA1111111111111111111111',
    documents: { identity: true, passport: true, license: true, photo: true },
    status: REQUEST_STATUS.PENDING_HR,
    companyId: 'comp-1',
    warehouseId: 'wh-1',
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-09-05',
  },
  {
    id: 'APP-2026-1045',
    fullName: 'خالد عمر الدوسري',
    nationalId: '1076543210',
    nationality: 'سعودي',
    dateOfBirth: '1989-11-24',
    phone: '541122334',
    city: 'Dammam',
    supervisorId: 'sup-noura',
    supervisorName: 'نورة القحطاني',
    supervisorPhone: '+966509876543',
    hasVehicle: true,
    vehiclePlate: 'س ص ع ٥٦٧٨',
    vehicleType: 'Cargo van',
    bankName: 'Al Rajhi Bank',
    iban: 'SA2222222222222222222222',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_ABSHER,
    companyId: 'comp-2',
    warehouseId: 'wh-3',
    sanadNumber: 'SND-99881',
    sanadDate: '2026-09-05',
    sanadAmount: '5000',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-09-04',
  },
  {
    id: 'APP-2026-1042',
    fullName: 'أحمد سالم الحربي',
    nationalId: '1065432109',
    nationality: 'سعودي',
    dateOfBirth: '1992-06-19',
    phone: '533445566',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ح ط ي ٩٩١٢',
    vehicleType: 'Sedan',
    bankName: 'Al Rajhi Bank',
    iban: 'SA3333333333333333333333',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.ACTIVE,
    companyId: 'comp-1',
    warehouseId: 'wh-1',
    sanadNumber: 'SND-77120',
    sanadDate: '2026-08-20',
    sanadAmount: '4500',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-08-18',
  },
  {
    id: 'APP-2026-1041',
    fullName: 'ياسر فهد المطيري',
    nationalId: '1054321098',
    nationality: 'سعودي',
    dateOfBirth: '1997-03-02',
    phone: '544556677',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: false,
    vehiclePlate: '',
    vehicleType: '',
    bankName: 'Riyad Bank',
    iban: 'SA4444444444444444444444',
    documents: { identity: true, license: true, photo: true },
    status: REQUEST_STATUS.PENDING_SUPERVISOR,
    companyId: null,
    warehouseId: null,
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: null,
    supervisorRejectReason: '',
    createdAt: '2026-09-08',
  },
  {
    id: 'APP-2026-1040',
    fullName: 'بندر ناصر العتيبي',
    nationalId: '1043210987',
    nationality: 'سعودي',
    dateOfBirth: '1993-12-11',
    phone: '555667788',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ب ن د ٣٣٤٤',
    vehicleType: 'Cargo van',
    bankName: 'Al Rajhi Bank',
    iban: 'SA5555555555555555555555',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_CONTRACT,
    companyId: 'comp-1',
    warehouseId: 'wh-2',
    sanadNumber: 'SND-88231',
    sanadDate: '2026-09-01',
    sanadAmount: '5200',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-08-28',
  },
  {
    id: 'APP-2026-1039',
    fullName: 'عمر ياسر الزهراني',
    nationalId: '1032109876',
    nationality: 'سعودي',
    dateOfBirth: '1995-01-27',
    phone: '566778899',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ع م ر ١١٩٨',
    vehicleType: 'Sedan',
    bankName: 'Al Rajhi Bank',
    iban: 'SA6666666666666666666666',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.ACTIVE,
    companyId: 'comp-2',
    warehouseId: 'wh-3',
    sanadNumber: 'SND-66011',
    sanadDate: '2026-08-12',
    sanadAmount: '4700',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-08-10',
  },
  {
    id: 'APP-2026-1038',
    fullName: 'ماجد سعد القرني',
    nationalId: '1021098765',
    nationality: 'سعودي',
    dateOfBirth: '1990-09-14',
    phone: '577889900',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: false,
    vehiclePlate: '',
    vehicleType: '',
    bankName: 'Riyad Bank',
    iban: 'SA7777777777777777777777',
    documents: { identity: true, license: true, photo: true },
    status: REQUEST_STATUS.ACTIVE,
    companyId: 'comp-1',
    warehouseId: 'wh-2',
    sanadNumber: 'SND-64021',
    sanadDate: '2026-07-30',
    sanadAmount: '4200',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-07-28',
  },
  {
    id: 'APP-2026-1037',
    fullName: 'طلال حسن الشمري',
    nationalId: '1010987654',
    nationality: 'سعودي',
    dateOfBirth: '1998-05-08',
    phone: '588990011',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ط ل ل ٨٨٧٧',
    vehicleType: 'Sedan',
    bankName: 'Al Rajhi Bank',
    iban: 'SA8888888888888888888888',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_SUPERVISOR,
    companyId: null,
    warehouseId: null,
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: null,
    supervisorRejectReason: '',
    createdAt: '2026-09-10',
  },
  {
    id: 'APP-2026-1036',
    fullName: 'ريان خالد العمري',
    nationalId: '1009876543',
    nationality: 'سعودي',
    dateOfBirth: '1996-11-30',
    phone: '599001122',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ر ي ن ٥٥٤٤',
    vehicleType: 'Cargo van',
    bankName: 'Al Rajhi Bank',
    iban: 'SA9999999999999999999999',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_HR,
    companyId: 'comp-1',
    warehouseId: 'wh-1',
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-09-09',
  },
  {
    id: 'APP-2026-1035',
    fullName: 'فيصل نايف الدوسري',
    nationalId: '1099887766',
    nationality: 'سعودي',
    dateOfBirth: '1988-07-21',
    phone: '512233445',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ف ص ل ٢٢٣٣',
    vehicleType: 'Sedan',
    bankName: 'Riyad Bank',
    iban: 'SA1010101010101010101010',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_ABSHER,
    companyId: 'comp-2',
    warehouseId: 'wh-4',
    sanadNumber: 'SND-55440',
    sanadDate: '2026-09-03',
    sanadAmount: '6100',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-09-02',
  },
  {
    id: 'APP-2026-1034',
    fullName: 'سلطان عبدالعزيز السبيعي',
    nationalId: '1088776655',
    nationality: 'سعودي',
    dateOfBirth: '1994-04-03',
    phone: '523344556',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'س ل ط ٦٦٥٥',
    vehicleType: 'Sedan',
    bankName: 'Al Rajhi Bank',
    iban: 'SA1212121212121212121212',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.ACTIVE,
    companyId: 'comp-1',
    warehouseId: 'wh-1',
    sanadNumber: 'SND-44009',
    sanadDate: '2026-07-15',
    sanadAmount: '4800',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-07-13',
  },
  {
    id: 'APP-2026-1033',
    fullName: 'نواف تركي المطيري',
    nationalId: '1077665544',
    nationality: 'سعودي',
    dateOfBirth: '1999-10-19',
    phone: '534455667',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: false,
    vehiclePlate: '',
    vehicleType: '',
    bankName: 'Riyad Bank',
    iban: 'SA1313131313131313131313',
    documents: { identity: true, license: true, photo: true },
    status: REQUEST_STATUS.CANCELLED,
    companyId: null,
    warehouseId: null,
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: CANCEL_REASON.SUPERVISOR_REJECTED,
    supervisorDecision: 'rejected',
    supervisorRejectReason: 'المستندات غير مكتملة وغير واضحة.',
    createdAt: '2026-08-05',
  },
  {
    id: 'APP-2026-1032',
    fullName: 'مشعل فهد العسيري',
    nationalId: '1066554433',
    nationality: 'سعودي',
    dateOfBirth: '2000-02-25',
    phone: '545566778',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: false,
    vehiclePlate: '',
    vehicleType: '',
    bankName: 'Al Rajhi Bank',
    iban: 'SA1414141414141414141414',
    documents: { identity: true, license: true, photo: true },
    status: REQUEST_STATUS.PENDING_SUPERVISOR,
    companyId: null,
    warehouseId: null,
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: null,
    supervisorRejectReason: '',
    createdAt: '2026-09-11',
  },
  {
    id: 'APP-2026-1031',
    fullName: 'راكان سامي الجهني',
    nationalId: '1055443322',
    nationality: 'سعودي',
    dateOfBirth: '1993-08-08',
    phone: '556677889',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'ر ك ن ٧٧٦٦',
    vehicleType: 'Cargo van',
    bankName: 'Riyad Bank',
    iban: 'SA1515151515151515151515',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.ACTIVE,
    companyId: 'comp-2',
    warehouseId: 'wh-3',
    sanadNumber: 'SND-33012',
    sanadDate: '2026-07-02',
    sanadAmount: '5000',
    cancelReason: null,
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
    createdAt: '2026-06-30',
  },
  {
    id: 'APP-2026-1030',
    fullName: 'وليد أحمد الشهري',
    nationalId: '1044332211',
    nationality: 'سعودي',
    dateOfBirth: '1997-06-15',
    phone: '567788990',
    city: 'Riyadh',
    supervisorId: 'sup-khaled',
    supervisorName: 'خالد عبدالله',
    supervisorPhone: '+966500000000',
    hasVehicle: true,
    vehiclePlate: 'و ل د ٤٤٣٣',
    vehicleType: 'Sedan',
    bankName: 'Al Rajhi Bank',
    iban: 'SA1616161616161616161616',
    documents: { identity: true, license: true, vehicle: true, photo: true },
    status: REQUEST_STATUS.PENDING_SUPERVISOR,
    companyId: null,
    warehouseId: null,
    sanadNumber: '',
    sanadDate: '',
    sanadAmount: '',
    cancelReason: null,
    supervisorDecision: null,
    supervisorRejectReason: '',
    createdAt: '2026-09-12',
  },
];

/* ----------------------------------------------------------------------------
 * طلبات العمليات (Operations requests)
 * -------------------------------------------------------------------------- */
export const MOCK_OPERATION_REQUESTS = [
  {
    id: 'REQ-092',
    title: 'تفويض مركبة',
    titleEn: 'Vehicle Authorization',
    category: 'financial',
    categoryLabelAr: 'مالي',
    categoryLabelEn: 'Financial',
    date: '24 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.APPROVED,
    notes: 'تم اعتماد تفويض سيارة للمندوب.',
    notesEn: 'A vehicle authorization was approved for the courier.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-091',
    title: 'تغيير الحساب البنكي',
    titleEn: 'Change Bank Account',
    category: 'financial',
    categoryLabelAr: 'مالي',
    categoryLabelEn: 'Financial',
    date: 'اليوم',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.PENDING_SUPERVISOR,
    notes: 'تحديث الآيبان لاستلام المستحقات.',
    notesEn: 'Bank account update to receive dues.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-090',
    title: 'طلب إجازة',
    titleEn: 'Leave Request',
    category: 'admin',
    categoryLabelAr: 'إداري',
    categoryLabelEn: 'Administrative',
    date: 'اليوم',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.PENDING_SUPERVISOR,
    notes: 'إجازة كاملة لمدة 3 أيام.',
    notesEn: 'Full leave for 3 days.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-089',
    title: 'صيانة المركبة',
    titleEn: 'Vehicle Maintenance',
    category: 'vehicle',
    categoryLabelAr: 'مركبة',
    categoryLabelEn: 'Vehicle',
    date: 'اليوم',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.PENDING_SUPERVISOR,
    notes: 'صيانة طارئة بسبب عطل في الفرامل.',
    notesEn: 'Emergency maintenance due to a brake fault.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-088',
    title: 'شكوى عامة',
    titleEn: 'General Complaint',
    category: 'admin',
    categoryLabelAr: 'إداري',
    categoryLabelEn: 'Administrative',
    date: 'أمس',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.PENDING_SUPERVISOR,
    notes: 'شكوى ضد عميل أثناء التوصيل.',
    notesEn: 'Complaint against a customer during delivery.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-087',
    title: 'سلفة مالية',
    titleEn: 'Financial Advance',
    category: 'financial',
    categoryLabelAr: 'مالي',
    categoryLabelEn: 'Financial',
    date: 'أمس',
    amount: '1,500 ر.س',
    amountEn: '1,500 SAR',
    status: OPERATION_STATUS.PENDING_SUPERVISOR,
    notes: 'سلفة تخصم من مستحقات الشهر القادم.',
    notesEn: 'Advance to be deducted from next month’s earnings.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-086',
    title: 'بدل فاقد وقود',
    titleEn: 'Fuel Card Replacement',
    category: 'vehicle',
    categoryLabelAr: 'مركبة',
    categoryLabelEn: 'Vehicle',
    date: '20 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.APPROVED,
    notes: 'بدل فاقد بطاقة وقود.',
    notesEn: 'Fuel card replacement.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-085',
    title: 'سلفة مالية',
    titleEn: 'Financial Advance',
    category: 'financial',
    categoryLabelAr: 'مالي',
    categoryLabelEn: 'Financial',
    date: 'اليوم',
    amount: '1,000 ر.س',
    amountEn: '1,000 SAR',
    status: OPERATION_STATUS.PENDING_HR,
    notes: 'طلب سلفة تخصم من مستحقات الشهر القادم.',
    notesEn: 'Advance request to be deducted from next month’s earnings.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-084',
    title: 'أدوات وزي التوصيل',
    titleEn: 'Delivery Tools & Uniform',
    category: 'admin',
    categoryLabelAr: 'إداري',
    categoryLabelEn: 'Administrative',
    date: '19 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.PENDING_HR,
    notes: 'طلب خوذة وزي رسمي.',
    notesEn: 'Helmet and uniform request.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-074',
    title: 'صيانة المركبة',
    titleEn: 'Vehicle Maintenance',
    category: 'vehicle',
    categoryLabelAr: 'مركبة',
    categoryLabelEn: 'Vehicle',
    date: '18 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.APPROVED,
    notes: 'تغيير إطارات وفحص الفرامل.',
    notesEn: 'Tire replacement and brake inspection.',
    requesterRole: 'courier',
    supervisorId: 'sup-khaled',
    supervisorDecision: 'approved',
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-061',
    title: 'طلب إجازة',
    titleEn: 'Leave Request',
    category: 'admin',
    categoryLabelAr: 'إداري',
    categoryLabelEn: 'Administrative',
    date: '12 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.REJECTED,
    notes: 'تعذر الموافقة بسبب ضغط الطلبات التشغيلية في النطاق.',
    notesEn: 'Declined due to high operational dispatch volumes in the zone.',
    requesterRole: 'courier',
    supervisorId: 'sup-fahad',
    supervisorDecision: 'rejected',
    supervisorRejectReason: 'ضغط الطلبات التشغيلية في النطاق.',
  },

  /* --------------------------------------------------------------------------
   * طلبات المشرف نفسه (requesterRole: 'supervisor')
   * تذهب مباشرة إلى HR ولا تظهر في صفحة مراجعة طلبات المشرف.
   * ------------------------------------------------------------------------ */
  {
    id: 'REQ-083',
    title: 'سلفة مالية',
    titleEn: 'Financial Advance',
    category: 'financial',
    categoryLabelAr: 'مالي',
    categoryLabelEn: 'Financial',
    date: 'اليوم',
    amount: '2,000 ر.س',
    amountEn: '2,000 SAR',
    status: OPERATION_STATUS.PENDING_HR,
    notes: 'طلب سلفة خاص بالمشرف.',
    notesEn: 'Supervisor personal advance request.',
    requesterRole: 'supervisor',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
  {
    id: 'REQ-082',
    title: 'تغيير نطاق العمل',
    titleEn: 'Change Work Zone',
    category: 'admin',
    categoryLabelAr: 'إداري',
    categoryLabelEn: 'Administrative',
    date: '21 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.APPROVED,
    notes: 'نقل نطاق العمل إلى شمال الرياض.',
    notesEn: 'Move work zone to north Riyadh.',
    requesterRole: 'supervisor',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
    hrDecision: 'approve',
  },
  {
    id: 'REQ-081',
    title: 'صيانة المركبة',
    titleEn: 'Vehicle Maintenance',
    category: 'vehicle',
    categoryLabelAr: 'مركبة',
    categoryLabelEn: 'Vehicle',
    date: '20 أكتوبر 2026',
    amount: null,
    amountEn: null,
    status: OPERATION_STATUS.PENDING_HR,
    notes: 'صيانة دورية لمركبة المشرف.',
    notesEn: 'Routine maintenance for the supervisor vehicle.',
    requesterRole: 'supervisor',
    supervisorId: 'sup-khaled',
    supervisorDecision: null,
    supervisorRejectReason: '',
  },
];
